
/** @type {dataLoggerConfig} */
const config = {
  deviceInfo: {},
  dataLoggerInfo: {
    data_logger_seq: 1,
    data_logger_def_seq: 1,
    main_seq: 1,
    dl_real_id: 'D_PV_1_001',
    dl_id: 'D_PV_001',
    dl_name: 'PV 001',
    m_name: '냉각형 태양광',
    dl_target_code: '001',
    dld_target_name: 'PV',
    dld_target_prefix: 'D_PV',
    serial_number: null,
    connect_info: {
      type: 'socket',
      // type: 'serial',
      subType: 'parser',
      addConfigInfo: { parser: 'readLineParser', option: '\r' },
      baudRate: 9600,
      port: 9000,
      // port: 'COM8',
      host: 'localhost',
    },
    protocol_info: { mainCategory: 'Sensor', subCategory: 'EanEnv' },
  },
  nodeList: [
    {
      node_seq: 12,
      node_def_seq: 8,
      node_class_seq: 6,
      data_logger_seq: 7,
      main_seq: 1,
      node_id: 'T_PR_001',
      node_real_id: 'T_PR_1_001',
      node_name: '모듈 후면 온도 001',
      dl_real_id: 'D_E_1_001',
      dl_id: 'D_E_001',
      dl_name: 'Environment (외기 환경) 001',
      data_unit: '℃',
      is_sensor: 1,
      is_avg_center: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'pvRearTemperature',
      nd_target_name: '모듈 후면 온도',
      nd_target_prefix: 'T_PR',
      nd_description: '섭씨: 1 atm에서의 물의 어는점을 0도, 끓는점을 100도로 정한 온도',
      nc_target_id: 'temp',
      nc_target_name: '온도',
      nc_description: '섭씨: 1 atm에서의 물의 어는점을 0도, 끓는점을 100도로 정한 온도',
    },
    {
      node_seq: 14,
      node_def_seq: 9,
      node_class_seq: 6,
      data_logger_seq: 7,
      main_seq: 1,
      node_id: 'T_W_001',
      node_real_id: 'T_W_1_001',
      node_name: '수중 온도 001',
      dl_real_id: 'D_E_1_001',
      dl_id: 'D_E_001',
      dl_name: 'Environment (외기 환경) 001',
      data_unit: '℃',
      is_sensor: 1,
      is_avg_center: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'waterTemperature',
      nd_target_name: '수중 온도',
      nd_target_prefix: 'T_W',
      nd_description: '섭씨: 1 atm에서의 물의 어는점을 0도, 끓는점을 100도로 정한 온도',
      nc_target_id: 'temp',
      nc_target_name: '온도',
      nc_description: '섭씨: 1 atm에서의 물의 어는점을 0도, 끓는점을 100도로 정한 온도',
    },
    {
      node_seq: 16,
      node_def_seq: 10,
      node_class_seq: 6,
      data_logger_seq: 7,
      main_seq: 1,
      node_id: 'T_OA_001',
      node_real_id: 'T_OA_1_001',
      node_name: '외기 온도 001',
      dl_real_id: 'D_E_1_001',
      dl_id: 'D_E_001',
      dl_name: 'Environment (외기 환경) 001',
      data_unit: '℃',
      is_sensor: 1,
      is_avg_center: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'outsideAirTemperature',
      nd_target_name: '외기 온도',
      nd_target_prefix: 'T_OA',
      nd_description: '섭씨: 1 atm에서의 물의 어는점을 0도, 끓는점을 100도로 정한 온도',
      nc_target_id: 'temp',
      nc_target_name: '온도',
      nc_description: '섭씨: 1 atm에서의 물의 어는점을 0도, 끓는점을 100도로 정한 온도',
    },
    {
      node_seq: 13,
      node_def_seq: 8,
      node_class_seq: 6,
      data_logger_seq: 8,
      main_seq: 1,
      node_id: 'T_PR_002',
      node_real_id: 'T_PR_1_002',
      node_name: '모듈 후면 온도 002',
      dl_real_id: 'D_E_1_002',
      dl_id: 'D_E_002',
      dl_name: 'Environment (외기 환경) 002',
      data_unit: '℃',
      is_sensor: 1,
      is_avg_center: 1,
      data_logger_index: 0,
      n_target_code: '002',
      nd_target_id: 'pvRearTemperature',
      nd_target_name: '모듈 후면 온도',
      nd_target_prefix: 'T_PR',
      nd_description: '섭씨: 1 atm에서의 물의 어는점을 0도, 끓는점을 100도로 정한 온도',
      nc_target_id: 'temp',
      nc_target_name: '온도',
      nc_description: '섭씨: 1 atm에서의 물의 어는점을 0도, 끓는점을 100도로 정한 온도',
    },
    {
      node_seq: 15,
      node_def_seq: 9,
      node_class_seq: 6,
      data_logger_seq: 8,
      main_seq: 1,
      node_id: 'T_W_002',
      node_real_id: 'T_W_1_002',
      node_name: '수중 온도 002',
      dl_real_id: 'D_E_1_002',
      dl_id: 'D_E_002',
      dl_name: 'Environment (외기 환경) 002',
      data_unit: '℃',
      is_sensor: 1,
      is_avg_center: 1,
      data_logger_index: 0,
      n_target_code: '002',
      nd_target_id: 'waterTemperature',
      nd_target_name: '수중 온도',
      nd_target_prefix: 'T_W',
      nd_description: '섭씨: 1 atm에서의 물의 어는점을 0도, 끓는점을 100도로 정한 온도',
      nc_target_id: 'temp',
      nc_target_name: '온도',
      nc_description: '섭씨: 1 atm에서의 물의 어는점을 0도, 끓는점을 100도로 정한 온도',
    },
  ],
};
module.exports = config;
