const placeList = [
  {
    place_seq: 511,
    place_def_seq: 62,
    place_class_seq: 41,
    main_seq: 2,
    uuid: 'bbbbb',
    m_name: '100kW 급',
    place_id: 'SEB_1',
    place_real_id: 'SEB_2_1',
    place_name: '수중 태양광 발전 증발지 1',
    p_target_code: '1',
    p_target_name: null,
    depth: 5,
    place_info: {
      thresholdConfigList: [
        {
          ndId: 'waterLevel',
          maxValue: { value: 10, isCall: false },
          upperLimitValue: { value: 7, isCall: false },
          setValue: { value: 5 },
          lowerLimitValue: { value: 2.9, isCall: true },
          minValue: { value: 1, isCall: true },
          callPlaceRankList: ['BW_2'],
          putPlaceRankList: ['BW_2', 'SEA'],
        },
        {
          ndId: 'salinity',
          upperLimitValue: { value: 10.5, isCall: false, isGroup: true },
          putPlaceRankList: ['BW_3', 'BW_2'],
          groupPlaceList: ['SEB_1', 'SEB_2', 'SEB_3', 'SEB_4', 'SEB_5'],
        },
        {
          ndId: 'moduleRearTemperature',
          upperLimitValue: { value: 40, isCall: true },
          callPlaceRankList: ['BW_2'],
          putPlaceRankList: ['BW_2'],
        },
      ],
      placeSize: { width: 356, height: 2800, depth: 15 },
    },
    chart_color: null,
    chart_sort_rank: null,
    pd_target_prefix: 'SEB',
    pd_target_id: 'solarEvaporationBlock',
    pd_target_name: '수중 태양광 발전 증발지',
    pc_target_id: 'salternBlock',
    pc_target_name: '염판',
    pc_description: null,
  },
  {
    place_seq: 512,
    place_def_seq: 62,
    place_class_seq: 41,
    main_seq: 2,
    uuid: 'bbbbb',
    m_name: '100kW 급',
    place_id: 'SEB_2',
    place_real_id: 'SEB_2_2',
    place_name: '수중 태양광 발전 증발지 2',
    p_target_code: '2',
    p_target_name: null,
    depth: 5,
    place_info: {
      thresholdConfigList: [
        {
          ndId: 'waterLevel',
          maxValue: { value: 10, isCall: false },
          upperLimitValue: { value: 7, isCall: false },
          setValue: { value: 5 },
          lowerLimitValue: { value: 2.9, isCall: true },
          minValue: { value: 1, isCall: true },
          callPlaceRankList: ['BW_2'],
          putPlaceRankList: ['BW_2', 'SEA'],
        },
        {
          ndId: 'salinity',
          upperLimitValue: { value: 10.5, isCall: false, isGroup: true },
          putPlaceRankList: ['BW_3', 'BW_2'],
          groupPlaceList: ['SEB_1', 'SEB_2', 'SEB_3', 'SEB_4', 'SEB_5'],
        },
        {
          ndId: 'moduleRearTemperature',
          upperLimitValue: { value: 40, isCall: true },
          callPlaceRankList: ['BW_2'],
          putPlaceRankList: ['BW_2'],
        },
      ],
      placeSize: { width: 356, height: 2800, depth: 15 },
    },
    chart_color: null,
    chart_sort_rank: null,
    pd_target_prefix: 'SEB',
    pd_target_id: 'solarEvaporationBlock',
    pd_target_name: '수중 태양광 발전 증발지',
    pc_target_id: 'salternBlock',
    pc_target_name: '염판',
    pc_description: null,
  },
  {
    place_seq: 513,
    place_def_seq: 62,
    place_class_seq: 41,
    main_seq: 2,
    uuid: 'bbbbb',
    m_name: '100kW 급',
    place_id: 'SEB_3',
    place_real_id: 'SEB_2_3',
    place_name: '수중 태양광 발전 증발지 3',
    p_target_code: '3',
    p_target_name: null,
    depth: 5,
    place_info: {
      thresholdConfigList: [
        {
          ndId: 'waterLevel',
          maxValue: { value: 10, isCall: false },
          upperLimitValue: { value: 7, isCall: false },
          setValue: { value: 5 },
          lowerLimitValue: { value: 2.9, isCall: true },
          minValue: { value: 1, isCall: true },
          callPlaceRankList: ['BW_2'],
          putPlaceRankList: ['BW_2', 'SEA'],
        },
        {
          ndId: 'salinity',
          upperLimitValue: { value: 10.5, isCall: false, isGroup: true },
          putPlaceRankList: ['BW_3', 'BW_2'],
          groupPlaceList: ['SEB_1', 'SEB_2', 'SEB_3', 'SEB_4', 'SEB_5'],
        },
        {
          ndId: 'moduleRearTemperature',
          upperLimitValue: { value: 40, isCall: true },
          callPlaceRankList: ['BW_2'],
          putPlaceRankList: ['BW_2'],
        },
      ],
      placeSize: { width: 356, height: 2800, depth: 15 },
    },
    chart_color: null,
    chart_sort_rank: null,
    pd_target_prefix: 'SEB',
    pd_target_id: 'solarEvaporationBlock',
    pd_target_name: '수중 태양광 발전 증발지',
    pc_target_id: 'salternBlock',
    pc_target_name: '염판',
    pc_description: null,
  },
  {
    place_seq: 514,
    place_def_seq: 62,
    place_class_seq: 41,
    main_seq: 2,
    uuid: 'bbbbb',
    m_name: '100kW 급',
    place_id: 'SEB_4',
    place_real_id: 'SEB_2_4',
    place_name: '수중 태양광 발전 증발지 4',
    p_target_code: '4',
    p_target_name: null,
    depth: 5,
    place_info: {
      thresholdConfigList: [
        {
          ndId: 'waterLevel',
          maxValue: { value: 10, isCall: false },
          upperLimitValue: { value: 7, isCall: false },
          setValue: { value: 5 },
          lowerLimitValue: { value: 2.9, isCall: true },
          minValue: { value: 1, isCall: true },
          callPlaceRankList: ['BW_2'],
          putPlaceRankList: ['BW_2', 'SEA'],
        },
        {
          ndId: 'salinity',
          upperLimitValue: { value: 10.5, isCall: false, isGroup: true },
          putPlaceRankList: ['BW_3', 'BW_2'],
          groupPlaceList: ['SEB_1', 'SEB_2', 'SEB_3', 'SEB_4', 'SEB_5'],
        },
        {
          ndId: 'moduleRearTemperature',
          upperLimitValue: { value: 40, isCall: true },
          callPlaceRankList: ['BW_2'],
          putPlaceRankList: ['BW_2'],
        },
      ],
      placeSize: { width: 356, height: 2800, depth: 15 },
    },
    chart_color: null,
    chart_sort_rank: null,
    pd_target_prefix: 'SEB',
    pd_target_id: 'solarEvaporationBlock',
    pd_target_name: '수중 태양광 발전 증발지',
    pc_target_id: 'salternBlock',
    pc_target_name: '염판',
    pc_description: null,
  },
  {
    place_seq: 515,
    place_def_seq: 62,
    place_class_seq: 41,
    main_seq: 2,
    uuid: 'bbbbb',
    m_name: '100kW 급',
    place_id: 'SEB_5',
    place_real_id: 'SEB_2_5',
    place_name: '수중 태양광 발전 증발지 5',
    p_target_code: '5',
    p_target_name: null,
    depth: 5,
    place_info: {
      thresholdConfigList: [
        {
          ndId: 'waterLevel',
          maxValue: { value: 10, isCall: false },
          upperLimitValue: { value: 7, isCall: false },
          setValue: { value: 5 },
          lowerLimitValue: { value: 2.9, isCall: true },
          minValue: { value: 1, isCall: true },
          callPlaceRankList: ['BW_2'],
          putPlaceRankList: ['BW_2', 'SEA'],
        },
        {
          ndId: 'salinity',
          upperLimitValue: { value: 10.5, isCall: false, isGroup: true },
          putPlaceRankList: ['BW_3', 'BW_2'],
          groupPlaceList: ['SEB_1', 'SEB_2', 'SEB_3', 'SEB_4', 'SEB_5'],
        },
        {
          ndId: 'moduleRearTemperature',
          upperLimitValue: { value: 40, isCall: true },
          callPlaceRankList: ['BW_2'],
          putPlaceRankList: ['BW_2'],
        },
      ],
      placeSize: { width: 356, height: 2800, depth: 15 },
    },
    chart_color: null,
    chart_sort_rank: null,
    pd_target_prefix: 'SEB',
    pd_target_id: 'solarEvaporationBlock',
    pd_target_name: '수중 태양광 발전 증발지',
    pc_target_id: 'salternBlock',
    pc_target_name: '염판',
    pc_description: null,
  },
  {
    place_seq: 516,
    place_def_seq: 62,
    place_class_seq: 41,
    main_seq: 2,
    uuid: 'bbbbb',
    m_name: '100kW 급',
    place_id: 'SEB_6',
    place_real_id: 'SEB_2_6',
    place_name: '수중 태양광 발전 증발지 6',
    p_target_code: '6',
    p_target_name: null,
    depth: 5,
    place_info: {
      thresholdConfigList: [
        {
          ndId: 'waterLevel',
          maxValue: { value: 10, isCall: false },
          upperLimitValue: { value: 7, isCall: false },
          setValue: { value: 5 },
          lowerLimitValue: { value: 2.9, isCall: true },
          minValue: { value: 1, isCall: true },
          callPlaceRankList: ['BW_3'],
          putPlaceRankList: ['BW_3', 'SEA'],
        },
        {
          ndId: 'salinity',
          upperLimitValue: { value: 18, isCall: false, isGroup: true },
          putPlaceRankList: ['BW_4', 'BW_3'],
          groupPlaceList: ['SEB_6', 'SEB_7', 'SEB_8'],
        },
        {
          ndId: 'moduleRearTemperature',
          upperLimitValue: { value: 40, isCall: true },
          callPlaceRankList: ['BW_3'],
          putPlaceRankList: ['BW_3'],
        },
      ],
      placeSize: { width: 356, height: 2800, depth: 15 },
    },
    chart_color: null,
    chart_sort_rank: null,
    pd_target_prefix: 'SEB',
    pd_target_id: 'solarEvaporationBlock',
    pd_target_name: '수중 태양광 발전 증발지',
    pc_target_id: 'salternBlock',
    pc_target_name: '염판',
    pc_description: null,
  },
  {
    place_seq: 517,
    place_def_seq: 62,
    place_class_seq: 41,
    main_seq: 2,
    uuid: 'bbbbb',
    m_name: '100kW 급',
    place_id: 'SEB_7',
    place_real_id: 'SEB_2_7',
    place_name: '수중 태양광 발전 증발지 7',
    p_target_code: '7',
    p_target_name: null,
    depth: 5,
    place_info: {
      thresholdConfigList: [
        {
          ndId: 'waterLevel',
          maxValue: { value: 10, isCall: false },
          upperLimitValue: { value: 7, isCall: false },
          setValue: { value: 5 },
          lowerLimitValue: { value: 2.9, isCall: true },
          minValue: { value: 1, isCall: true },
          callPlaceRankList: ['BW_3'],
          putPlaceRankList: ['BW_3', 'SEA'],
        },
        {
          ndId: 'salinity',
          upperLimitValue: { value: 18, isCall: false, isGroup: true },
          putPlaceRankList: ['BW_4', 'BW_3'],
          groupPlaceList: ['SEB_6', 'SEB_7', 'SEB_8'],
        },
        {
          ndId: 'moduleRearTemperature',
          upperLimitValue: { value: 40, isCall: true },
          callPlaceRankList: ['BW_3'],
          putPlaceRankList: ['BW_3'],
        },
      ],
      placeSize: { width: 356, height: 2800, depth: 15 },
    },
    chart_color: null,
    chart_sort_rank: null,
    pd_target_prefix: 'SEB',
    pd_target_id: 'solarEvaporationBlock',
    pd_target_name: '수중 태양광 발전 증발지',
    pc_target_id: 'salternBlock',
    pc_target_name: '염판',
    pc_description: null,
  },
  {
    place_seq: 518,
    place_def_seq: 62,
    place_class_seq: 41,
    main_seq: 2,
    uuid: 'bbbbb',
    m_name: '100kW 급',
    place_id: 'SEB_8',
    place_real_id: 'SEB_2_8',
    place_name: '수중 태양광 발전 증발지 8',
    p_target_code: '8',
    p_target_name: null,
    depth: 5,
    place_info: {
      thresholdConfigList: [
        {
          ndId: 'waterLevel',
          maxValue: { value: 10, isCall: false },
          upperLimitValue: { value: 7, isCall: false },
          setValue: { value: 5 },
          lowerLimitValue: { value: 2.9, isCall: true },
          minValue: { value: 1, isCall: true },
          callPlaceRankList: ['BW_3'],
          putPlaceRankList: ['BW_3', 'SEA'],
        },
        {
          ndId: 'salinity',
          upperLimitValue: { value: 18, isCall: false, isGroup: true },
          putPlaceRankList: ['BW_4', 'BW_3'],
          groupPlaceList: ['SEB_6', 'SEB_7', 'SEB_8'],
        },
        {
          ndId: 'moduleRearTemperature',
          upperLimitValue: { value: 40, isCall: true },
          callPlaceRankList: ['BW_3'],
          putPlaceRankList: ['BW_3'],
        },
      ],
      placeSize: { width: 356, height: 2800, depth: 15 },
    },
    chart_color: null,
    chart_sort_rank: null,
    pd_target_prefix: 'SEB',
    pd_target_id: 'solarEvaporationBlock',
    pd_target_name: '수중 태양광 발전 증발지',
    pc_target_id: 'salternBlock',
    pc_target_name: '염판',
    pc_description: null,
  },

  {
    place_seq: 224,
    place_def_seq: 30,
    place_class_seq: 20,
    main_seq: 2,
    uuid: 'bbbbb',
    m_name: '100kW 급 TB',
    place_id: 'WW_017',
    place_real_id: 'WW_2_017',
    place_name: '수로 017',
    p_target_code: '017',
    p_target_name: null,
    depth: 0.5,
    place_info: null,
    chart_color: null,
    chart_sort_rank: null,
    pd_target_prefix: 'WW',
    pd_target_id: 'waterWay',
    pd_target_name: '수로',
    pc_target_id: 'waterWay',
    pc_target_name: '수로',
    pc_description: null,
  },
];

const nodeList = [
  {
    node_seq: 379,
    node_def_seq: 40,
    node_class_seq: 42,
    data_logger_seq: 83,
    main_seq: 2,
    node_id: 'BT_001',
    node_real_id: 'BT_2_001',
    node_name: '염수 온도 001',
    dl_real_id: 'D_GV_2_106',
    dl_id: 'D_GV_106',
    dl_name: '게이트형 밸브 106',
    data_unit: '℃',
    save_db_type: 'sensor',
    is_sensor: 1,
    is_avg_center: null,
    data_logger_index: 0,
    n_target_code: '001',
    nd_target_id: 'brineTemperature',
    nd_target_name: '염수 온도',
    nd_target_prefix: 'BT',
    nd_description: '섭씨',
    nc_target_id: 'temp',
    nc_target_name: '온도',
    nc_description: '섭씨',
  },
  {
    node_seq: 380,
    node_def_seq: 41,
    node_class_seq: 42,
    data_logger_seq: 83,
    main_seq: 2,
    node_id: 'MRT_001',
    node_real_id: 'MRT_2_001',
    node_name: '모듈 뒷면 온도 001',
    dl_real_id: 'D_GV_2_106',
    dl_id: 'D_GV_106',
    dl_name: '게이트형 밸브 106',
    data_unit: '℃',
    save_db_type: 'sensor',
    is_sensor: 1,
    is_avg_center: null,
    data_logger_index: 0,
    n_target_code: '001',
    nd_target_id: 'moduleRearTemperature',
    nd_target_name: '모듈 뒷면 온도',
    nd_target_prefix: 'MRT',
    nd_description: '섭씨',
    nc_target_id: 'temp',
    nc_target_name: '온도',
    nc_description: '섭씨',
  },
  {
    node_seq: 381,
    node_def_seq: 41,
    node_class_seq: 42,
    data_logger_seq: 85,
    main_seq: 2,
    node_id: 'MRT_002',
    node_real_id: 'MRT_2_002',
    node_name: '모듈 뒷면 온도 002',
    dl_real_id: 'D_GV_2_108',
    dl_id: 'D_GV_108',
    dl_name: '게이트형 밸브 108',
    data_unit: '℃',
    save_db_type: 'sensor',
    is_sensor: 1,
    is_avg_center: null,
    data_logger_index: 0,
    n_target_code: '002',
    nd_target_id: 'moduleRearTemperature',
    nd_target_name: '모듈 뒷면 온도',
    nd_target_prefix: 'MRT',
    nd_description: '섭씨',
    nc_target_id: 'temp',
    nc_target_name: '온도',
    nc_description: '섭씨',
  },

  {
    node_seq: 389,
    node_def_seq: 42,
    node_class_seq: 43,
    data_logger_seq: 83,
    main_seq: 2,
    node_id: 'S_002',
    node_real_id: 'S_2_002',
    node_name: '염도 002',
    dl_real_id: 'D_GV_2_106',
    dl_id: 'D_GV_106',
    dl_name: '게이트형 밸브 106',
    data_unit: '%',
    save_db_type: 'sensor',
    is_sensor: 1,
    is_avg_center: null,
    data_logger_index: 0,
    n_target_code: '002',
    nd_target_id: 'salinity',
    nd_target_name: '염도',
    nd_target_prefix: 'S',
    nd_description: null,
    nc_target_id: 'salinity',
    nc_target_name: '염도',
    nc_description: null,
  },
  {
    node_seq: 390,
    node_def_seq: 42,
    node_class_seq: 43,
    data_logger_seq: 85,
    main_seq: 2,
    node_id: 'S_003',
    node_real_id: 'S_2_003',
    node_name: '염도 003',
    dl_real_id: 'D_GV_2_108',
    dl_id: 'D_GV_108',
    dl_name: '게이트형 밸브 108',
    data_unit: '%',
    save_db_type: 'sensor',
    is_sensor: 1,
    is_avg_center: null,
    data_logger_index: 0,
    n_target_code: '003',
    nd_target_id: 'salinity',
    nd_target_name: '염도',
    nd_target_prefix: 'S',
    nd_description: null,
    nc_target_id: 'salinity',
    nc_target_name: '염도',
    nc_description: null,
  },

  {
    node_seq: 404,
    node_def_seq: 43,
    node_class_seq: 44,
    data_logger_seq: 83,
    main_seq: 2,
    node_id: 'WL_008',
    node_real_id: 'WL_2_008',
    node_name: '수위 008',
    dl_real_id: 'D_GV_2_106',
    dl_id: 'D_GV_106',
    dl_name: '게이트형 밸브 106',
    data_unit: 'cm',
    save_db_type: 'sensor',
    is_sensor: 1,
    is_avg_center: null,
    data_logger_index: 0,
    n_target_code: '008',
    nd_target_id: 'waterLevel',
    nd_target_name: '수위',
    nd_target_prefix: 'WL',
    nd_description: null,
    nc_target_id: 'waterLevel',
    nc_target_name: '수위',
    nc_description: null,
  },
  {
    node_seq: 405,
    node_def_seq: 43,
    node_class_seq: 44,
    data_logger_seq: 85,
    main_seq: 2,
    node_id: 'WL_009',
    node_real_id: 'WL_2_009',
    node_name: '수위 009',
    dl_real_id: 'D_GV_2_108',
    dl_id: 'D_GV_108',
    dl_name: '게이트형 밸브 108',
    data_unit: 'cm',
    save_db_type: 'sensor',
    is_sensor: 1,
    is_avg_center: null,
    data_logger_index: 0,
    n_target_code: '009',
    nd_target_id: 'waterLevel',
    nd_target_name: '수위',
    nd_target_prefix: 'WL',
    nd_description: null,
    nc_target_id: 'waterLevel',
    nc_target_name: '수위',
    nc_description: null,
  },
];

const placeRelationList = [
  {
    place_relation_seq: 896,
    node_seq: 379,
    place_seq: 188,
    node_id: 'BT_001',
    node_real_id: 'BT_2_001',
    node_name: '염수 온도 001',
    dl_id: 'D_GV_106',
    dl_name: '게이트형 밸브 106',
    place_id: 'SEB_1',
    place_name: '수중 태양광 발전 증발지 1',
    chart_color: null,
    chart_sort_rank: null,
    pd_target_name: '수중 태양광 발전 증발지',
    nc_target_name: '온도',
    nd_target_name: '염수 온도',
    is_sensor: 1,
    nd_target_id: 'brineTemperature',
    nc_target_id: 'temp',
    serial_number: '0013A20040F70106',
    main_seq: 2,
    data_logger_seq: 83,
  },
  {
    place_relation_seq: 895,
    node_seq: 380,
    place_seq: 188,
    node_id: 'MRT_001',
    node_real_id: 'MRT_2_001',
    node_name: '모듈 뒷면 온도 001',
    dl_id: 'D_GV_106',
    dl_name: '게이트형 밸브 106',
    place_id: 'SEB_1',
    place_name: '수중 태양광 발전 증발지 1',
    chart_color: null,
    chart_sort_rank: null,
    pd_target_name: '수중 태양광 발전 증발지',
    nc_target_name: '온도',
    nd_target_name: '모듈 뒷면 온도',
    is_sensor: 1,
    nd_target_id: 'moduleRearTemperature',
    nc_target_id: 'temp',
    serial_number: '0013A20040F70106',
    main_seq: 2,
    data_logger_seq: 83,
  },
  {
    place_relation_seq: 899,
    node_seq: 381,
    place_seq: 189,
    node_id: 'MRT_002',
    node_real_id: 'MRT_2_002',
    node_name: '모듈 뒷면 온도 002',
    dl_id: 'D_GV_108',
    dl_name: '게이트형 밸브 108',
    place_id: 'SEB_2',
    place_name: '수중 태양광 발전 증발지 2',
    chart_color: null,
    chart_sort_rank: null,
    pd_target_name: '수중 태양광 발전 증발지',
    nc_target_name: '온도',
    nd_target_name: '모듈 뒷면 온도',
    is_sensor: 1,
    nd_target_id: 'moduleRearTemperature',
    nc_target_id: 'temp',
    serial_number: '0013A20040F70108',
    main_seq: 2,
    data_logger_seq: 85,
  },

  {
    place_relation_seq: 925,
    node_seq: 388,
    place_seq: 197,
    node_id: 'S_001',
    node_real_id: 'S_2_001',
    node_name: '염도 001',
    dl_id: 'D_S_003',
    dl_name: '센서  003',
    place_id: 'NEB_2',
    place_name: '일반 증발지 2',
    chart_color: null,
    chart_sort_rank: null,
    pd_target_name: '일반 증발지',
    nc_target_name: '염도',
    nd_target_name: '염도',
    is_sensor: 1,
    nd_target_id: 'salinity',
    nc_target_id: 'salinity',
    serial_number: '0013A20040F71003',
    main_seq: 2,
    data_logger_seq: 114,
  },
  {
    place_relation_seq: 893,
    node_seq: 389,
    place_seq: 188,
    node_id: 'S_002',
    node_real_id: 'S_2_002',
    node_name: '염도 002',
    dl_id: 'D_GV_106',
    dl_name: '게이트형 밸브 106',
    place_id: 'SEB_1',
    place_name: '수중 태양광 발전 증발지 1',
    chart_color: null,
    chart_sort_rank: null,
    pd_target_name: '수중 태양광 발전 증발지',
    nc_target_name: '염도',
    nd_target_name: '염도',
    is_sensor: 1,
    nd_target_id: 'salinity',
    nc_target_id: 'salinity',
    serial_number: '0013A20040F70106',
    main_seq: 2,
    data_logger_seq: 83,
  },
  {
    place_relation_seq: 897,
    node_seq: 390,
    place_seq: 189,
    node_id: 'S_003',
    node_real_id: 'S_2_003',
    node_name: '염도 003',
    dl_id: 'D_GV_108',
    dl_name: '게이트형 밸브 108',
    place_id: 'SEB_2',
    place_name: '수중 태양광 발전 증발지 2',
    chart_color: null,
    chart_sort_rank: null,
    pd_target_name: '수중 태양광 발전 증발지',
    nc_target_name: '염도',
    nd_target_name: '염도',
    is_sensor: 1,
    nd_target_id: 'salinity',
    nc_target_id: 'salinity',
    serial_number: '0013A20040F70108',
    main_seq: 2,
    data_logger_seq: 85,
  },

  {
    place_relation_seq: 894,
    node_seq: 404,
    place_seq: 188,
    node_id: 'WL_008',
    node_real_id: 'WL_2_008',
    node_name: '수위 008',
    dl_id: 'D_GV_106',
    dl_name: '게이트형 밸브 106',
    place_id: 'SEB_1',
    place_name: '수중 태양광 발전 증발지 1',
    chart_color: null,
    chart_sort_rank: null,
    pd_target_name: '수중 태양광 발전 증발지',
    nc_target_name: '수위',
    nd_target_name: '수위',
    is_sensor: 1,
    nd_target_id: 'waterLevel',
    nc_target_id: 'waterLevel',
    serial_number: '0013A20040F70106',
    main_seq: 2,
    data_logger_seq: 83,
  },
  {
    place_relation_seq: 898,
    node_seq: 405,
    place_seq: 189,
    node_id: 'WL_009',
    node_real_id: 'WL_2_009',
    node_name: '수위 009',
    dl_id: 'D_GV_108',
    dl_name: '게이트형 밸브 108',
    place_id: 'SEB_2',
    place_name: '수중 태양광 발전 증발지 2',
    chart_color: null,
    chart_sort_rank: null,
    pd_target_name: '수중 태양광 발전 증발지',
    nc_target_name: '수위',
    nd_target_name: '수위',
    is_sensor: 1,
    nd_target_id: 'waterLevel',
    nc_target_id: 'waterLevel',
    serial_number: '0013A20040F70108',
    main_seq: 2,
    data_logger_seq: 85,
  },
];

module.exports = {
  placeList,
  nodeList,
  placeRelationList,
};
