/** @type {dataLoggerConfig} */
const config = {
  hasDev: false,
  deviceInfo: {},
  dataLoggerInfo: {
    data_logger_seq: 3,
    data_logger_def_seq: 7,
    main_seq: 1,
    dl_real_id: 'D_SB_1_001',
    dl_id: 'D_SB_001',
    dl_name: '센서 Board DL 001',
    m_name: '영산포',
    dl_target_code: '001',
    dld_target_name: '센서 Board DL',
    dld_target_prefix: 'D_SB',
    serial_number: '1',
    connect_info: {
      type: 'socket',
      baudRate: 9600,
      port: 9000,
    },
    // connect_info: {
    //   type: 'modbus',
    //   subType: 'rtu',
    //   baudRate: 9600,
    //   port: 'COM3',
    // },
    protocol_info: {
      mainCategory: 'FarmParallel',
      subCategory: 'YeongSanPo',
      // wrapperCategory: 'default',
      deviceId: 1,
    },
  },
  nodeList: [
    {
      node_seq: 1,
      node_def_seq: 1,
      node_class_seq: 1,
      data_logger_seq: 3,
      main_seq: 1,
      node_id: 'T_S_001',
      node_real_id: 'T_S_1_001',
      node_name: '토양 온도 001',
      dl_real_id: 'D_SB_1_001',
      dl_id: 'D_SB_001',
      dl_name: '센서 Board DL 001',
      data_unit: '℃',
      is_sensor: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'soilTemperature',
      nd_target_name: '토양 온도',
      nd_target_prefix: 'T_S',
      nd_description: '섭씨: 1 atm에서의 물의 어는점을 0도, 끓는점을 100도로 정한 온도',
      nc_target_id: 'temp',
      nc_target_name: '온도',
      nc_description: '섭씨: 1 atm에서의 물의 어는점을 0도, 끓는점을 100도로 정한 온도',
    },
    {
      node_seq: 3,
      node_def_seq: 2,
      node_class_seq: 1,
      data_logger_seq: 3,
      main_seq: 1,
      node_id: 'T_OA_001',
      node_real_id: 'T_OA_1_001',
      node_name: '외기 온도 001',
      dl_real_id: 'D_SB_1_001',
      dl_id: 'D_SB_001',
      dl_name: '센서 Board DL 001',
      data_unit: '℃',
      is_sensor: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'outsideAirTemperature',
      nd_target_name: '외기 온도',
      nd_target_prefix: 'T_OA',
      nd_description: '섭씨: 1 atm에서의 물의 어는점을 0도, 끓는점을 100도로 정한 온도',
      nc_target_id: 'temp',
      nc_target_name: '온도',
      nc_description: '섭씨: 1 atm에서의 물의 어는점을 0도, 끓는점을 100도로 정한 온도',
    },
    {
      node_seq: 5,
      node_def_seq: 3,
      node_class_seq: 2,
      data_logger_seq: 3,
      main_seq: 1,
      node_id: 'RH_S_001',
      node_real_id: 'RH_S_1_001',
      node_name: '토양 습도 001',
      dl_real_id: 'D_SB_1_001',
      dl_id: 'D_SB_001',
      dl_name: '센서 Board DL 001',
      data_unit: '%RH',
      is_sensor: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'soilReh',
      nd_target_name: '토양 습도',
      nd_target_prefix: 'RH_S',
      nd_description: '공기 중에 포함되어 있는 수증기의 양 또는 비율을 나타내는 단위',
      nc_target_id: 'reh',
      nc_target_name: '습도',
      nc_description: '공기 중에 포함되어 있는 수증기의 양 또는 비율을 나타내는 단위',
    },
    {
      node_seq: 7,
      node_def_seq: 4,
      node_class_seq: 2,
      data_logger_seq: 3,
      main_seq: 1,
      node_id: 'RH_OA_001',
      node_real_id: 'RH_OA_1_001',
      node_name: '외기 습도 001',
      dl_real_id: 'D_SB_1_001',
      dl_id: 'D_SB_001',
      dl_name: '센서 Board DL 001',
      data_unit: '%RH',
      is_sensor: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'outsideAirReh',
      nd_target_name: '외기 습도',
      nd_target_prefix: 'RH_OA',
      nd_description: '공기 중에 포함되어 있는 수증기의 양 또는 비율을 나타내는 단위',
      nc_target_id: 'reh',
      nc_target_name: '습도',
      nc_description: '공기 중에 포함되어 있는 수증기의 양 또는 비율을 나타내는 단위',
    },
    {
      node_seq: 9,
      node_def_seq: 5,
      node_class_seq: 3,
      data_logger_seq: 3,
      main_seq: 1,
      node_id: 'W_S_001',
      node_real_id: 'W_S_1_001',
      node_name: '풍속 001',
      dl_real_id: 'D_SB_1_001',
      dl_id: 'D_SB_001',
      dl_name: '센서 Board DL 001',
      data_unit: 'm/s',
      is_sensor: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'windSpeed',
      nd_target_name: '풍속',
      nd_target_prefix: 'W_S',
      nd_description: '초당 바람이 이동하는 거리(m)',
      nc_target_id: 'ws',
      nc_target_name: '풍속',
      nc_description: '초당 바람이 이동하는 거리(m)',
    },
    {
      node_seq: 11,
      node_def_seq: 6,
      node_class_seq: 4,
      data_logger_seq: 3,
      main_seq: 1,
      node_id: 'W_D_001',
      node_real_id: 'W_D_1_001',
      node_name: '풍향 001',
      dl_real_id: 'D_SB_1_001',
      dl_id: 'D_SB_001',
      dl_name: '센서 Board DL 001',
      data_unit: '°',
      is_sensor: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'windDirection',
      nd_target_name: '풍향',
      nd_target_prefix: 'W_D',
      nd_description: '바람이 불어오는 방향을 360 각도로 표현',
      nc_target_id: 'wd',
      nc_target_name: '풍향',
      nc_description: '바람이 불어오는 방향을 360 각도로 표현',
    },
    {
      node_seq: 13,
      node_def_seq: 7,
      node_class_seq: 5,
      data_logger_seq: 3,
      main_seq: 1,
      node_id: 'SL_001',
      node_real_id: 'SL_1_001',
      node_name: '일사량 001',
      dl_real_id: 'D_SB_1_001',
      dl_id: 'D_SB_001',
      dl_name: '센서 Board DL 001',
      data_unit: 'W/m²',
      is_sensor: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'solar',
      nd_target_name: '일사량',
      nd_target_prefix: 'SL',
      nd_description: '1평방 미터당 조사되는 일사에너지의 양이 1W',
      nc_target_id: 'solar',
      nc_target_name: '일사량',
      nc_description: '1평방 미터당 조사되는 일사에너지의 양이 1W',
    },
    {
      node_seq: 15,
      node_def_seq: 8,
      node_class_seq: 6,
      data_logger_seq: 3,
      main_seq: 1,
      node_id: 'RF1_001',
      node_real_id: 'RF1_1_001',
      node_name: '시간당 강우량 001',
      dl_real_id: 'D_SB_1_001',
      dl_id: 'D_SB_001',
      dl_name: '센서 Board DL 001',
      data_unit: 'mm/hr',
      is_sensor: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'r1',
      nd_target_name: '시간당 강우량',
      nd_target_prefix: 'RF1',
      nd_description: '시간당 일정한 곳에 내린 비의 분량. 단위는 mm',
      nc_target_id: 'rainfall',
      nc_target_name: '강우량',
      nc_description: '시간당 일정한 곳에 내린 비의 분량. 단위는 mm',
    },
    {
      node_seq: 17,
      node_def_seq: 9,
      node_class_seq: 7,
      data_logger_seq: 3,
      main_seq: 1,
      node_id: 'IR_001',
      node_real_id: 'IR_1_001',
      node_name: '강우 감지 여부 001',
      dl_real_id: 'D_SB_1_001',
      dl_id: 'D_SB_001',
      dl_name: '센서 Board DL 001',
      data_unit: null,
      is_sensor: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'isRain',
      nd_target_name: '강우 감지 여부',
      nd_target_prefix: 'IR',
      nd_description: '감지시 1, 미감지시 0',
      nc_target_id: 'isRain',
      nc_target_name: '강우 감지 여부',
      nc_description: '감지시 1, 미감지시 0',
    },
    {
      node_seq: 19,
      node_def_seq: 10,
      node_class_seq: 8,
      data_logger_seq: 3,
      main_seq: 1,
      node_id: 'CO2_001',
      node_real_id: 'CO2_1_001',
      node_name: '이산화탄소 001',
      dl_real_id: 'D_SB_1_001',
      dl_id: 'D_SB_001',
      dl_name: '센서 Board DL 001',
      data_unit: 'ppm',
      is_sensor: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'co2',
      nd_target_name: '이산화탄소',
      nd_target_prefix: 'CO2',
      nd_description: '백만분의 1. 이산화탄소 농도 395ppm = 395/1,000,000 * 100 = 0.0395 %',
      nc_target_id: 'co2',
      nc_target_name: '이산화탄소',
      nc_description: '백만분의 1. 이산화탄소 농도 395ppm = 395/1,000,000 * 100 = 0.0395 %',
    },
    {
      node_seq: 21,
      node_def_seq: 11,
      node_class_seq: 10,
      data_logger_seq: 3,
      main_seq: 1,
      node_id: 'LX_001',
      node_real_id: 'LX_1_001',
      node_name: '조도 001',
      dl_real_id: 'D_SB_1_001',
      dl_id: 'D_SB_001',
      dl_name: '센서 Board DL 001',
      data_unit: 'lx',
      is_sensor: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'lux',
      nd_target_name: '조도',
      nd_target_prefix: 'LX',
      nd_description: '1㎡의 면적 위에 1m의 광속이 균일하게 비춰질 때',
      nc_target_id: 'lux',
      nc_target_name: '조도',
      nc_description: '1㎡의 면적 위에 1m의 광속이 균일하게 비춰질 때',
    },
    {
      node_seq: 23,
      node_def_seq: 12,
      node_class_seq: 11,
      data_logger_seq: 3,
      main_seq: 1,
      node_id: 'WV_S_001',
      node_real_id: 'WV_S_1_001',
      node_name: '토양 수분 값 001',
      dl_real_id: 'D_SB_1_001',
      dl_id: 'D_SB_001',
      dl_name: '센서 Board DL 001',
      data_unit: '%',
      is_sensor: 1,
      data_logger_index: 0,
      n_target_code: '001',
      nd_target_id: 'soilWaterValue',
      nd_target_name: '토양 수분 값',
      nd_target_prefix: 'WV_S',
      nd_description: '',
      nc_target_id: 'waterValue',
      nc_target_name: '수분 값',
      nc_description: '',
    },
  ],
};
module.exports = config;
